#!/usr/bin/awk -f

# netmon_parser
# parse netmon's request headers list

# Netmon is a firefox extention which view the HTTP headers of the current page.
# URL: https://addons.mozilla.org/en-US/firefox/addon/netmon/

# Output example from example.com:
#	 @URL	https://example.com
#	 Accept	image/avif,image/webp,*/*
#	 Accept-Encoding	gzip, deflate
#	 Accept-Language	en-US,en;q=0.5
#	 Connection	keep-alive
#	 DNT	1
#	 Host	example.com
#	 Referer	http://example.com/
#	 User-Agent	Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0

BEGIN {
	# Enum
	General = 0
	Request = 1
	Response = 2

	Status = General
}

/^Request headers$/ {
	Status = Request
	next
}
/^Response headers$/ {
	Status = Response
	exit
}

/^Request URL:/ {
	sub(/^Request URL:/, "@URL\t")
	print
	next
}
Status == Request {
	sub(/:/, "\t")
	print
	next
}
