#!/bin/sh

# m3u8_parser - parse .m3u8 file and generate URL to download contents in the file for cURL.

URL=${1?}

awk -v URL_dir="$(dirname "$URL")" '
	BEGIN {
		gotten = 0
		URL_m3u8 = ""
	}
	/^#/ { next }
	{
		if (gotten == 0) {
			URL_m3u8 = $0
		}
		gotten = 1
		nline++
	}
	END {
		s=match(URL_m3u8, /-1-v1-a1/)
		if (s == 0) {
			exit 1
		}
		prefix=substr(URL_m3u8, 1, s)
		suffix=substr(URL_m3u8, s+RLENGTH-6)
		if (URL_m3u8 ~ /^http/) {
			printf("%s[1-%d]%s\n", prefix, nline, suffix)
		} else {
			printf("%s/%s[1-%d]%s\n", URL_dir, prefix, nline, suffix)
		}
	}'
