#!/bin/sh

usage() {
	cat >&2 <<EOF
usage: $0 [-o OUTPUT] [FILE]
  -o OUTPUT
     filename of a output, which is a .ts file. (default $output)
  -n
     not remove tempfile
EOF
	exit 1
}

progname=$(basename "$0")
fatal() {
	echo "$progname: failed!" >&2
	exit 1
}

TMPDIR=${TMPDIR:-/tmp}
output=out.ts
nflag=false
while getopts o:nh flag
do
	case "$flag" in
	o)	output="$OPTARG";;
	n)	nflag=true;;
	h|?)	usage;;
	esac
done
shift $((OPTIND-1))

case "$output" in
/*)	:;;
*)	output="$(pwd)/$output";;
esac

sh -c 'set -C; : > '"$output" || fatal

tmpdir=$(mktemp -d $TMPDIR/hls_tmpdir.$$.XXXXXXXXXX) || fatal
# get files and concatenate its into a .mp4
cat -- "$@" | (
	cd $tmpdir
	echo cd $(pwd) >&2
	netmon_m3u8_curl | tee /dev/fd/2 | sh

	# An ordinary filename of .ts is 'XXX-N-v1-a1' where N is a number
	ls * |
		sort -n -t - -k2,2 |
		xargs cat > "$output" || exit 1
) || fatal

# not use 'trap' in order to rest tmpfiles at fatal status
if [ $nflag = true ]
then
	echo "$progname: tempfiles are remained at $tmpdir" >&2
else
	rm -rf "$tmpdir"
fi
